import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  todoist: [{type: 'autogenerated', dirName: 'todoist'}],
  wonderlist: [{type: 'autogenerated', dirName: 'wonderlist'}]
};

export default sidebars;
