name: CI and Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t ticklr-app .

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Render CLI
        run: |
          curl -sSL https://render.com/deploy/render-cli/install.sh | bash

      - name: Authenticate with Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          export RENDER_API_KEY=${{ secrets.RENDER_API_KEY }}
          render login --api-key $RENDER_API_KEY

      - name: Deploy to Render
        env:
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          render deploy --service-id $RENDER_SERVICE_ID --branch main

